x-project:
  name: feedapp_project
services:
  feedapp:
    build:
      # Path to backend service
      context: ./FeedApp
    # Specify image- and container names for the feedapp service
    image: feedapp-image1.5:latest
    # Ensures that RabbitMQ is started and working before the backend
    depends_on:
      - rabbitmq
    ports:
      # Expose the backend on port 8080
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:4.0.1-management
    container_name: feedapp-rabbit-docker
    ports:
      - "5672:5672"    # RabbitMQ port
      - "15672:15672"  # RabbitMQ management UI on port 15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest