spring.application.name=FeedApp

spring.jpa.defer-datasource-initialization=true

# Show SQL queries and related logs
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.description.sql=trace
logging.level.org.springframework.web=debug

# Server port configuration
server.port=8080

# Postgres configuration
spring.datasource.driver-class-name=org.postresql.Driver
spring.datasource.url= ${db-url:jdbc:postgresql://172.17.0.2:5432/postgres_db}
spring.datasource.username=${db-username:postgres}
spring.datasource.password=${db-password:postgres}

# Hibernate will create and update schema in the postgreSQL database
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect