spring.application.name=FeedApp

server.port=8080

# MongoDB Configurations
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.host=${MONGODB_HOSTNAME}
spring.data.mongodb.port=${MONGODB_PORT}
spring.data.mongodb.database=${MONGODB_NAME}
spring.data.mongodb.username=${MONGODB_USERNAME}
spring.data.mongodb.password=${MONGODB_PASSWORD}
#spring.data.mongodb.uri=mongodb://172.19.0.3:27017/feedapp_db
#spring.data.mongodb.uri=mongodb://172.17.0.3:27017/feedapp_db
#spring.data.mongodb.database=feedapp_db
#spring.data.mongodb.port=27017
#spring.data.mongodb.username=admin
#spring.data.mongodb.password=admin
